version: '2'

services:
    redis:
        container_name: container_redis
        image: redis:alpine
        ports:
            - "6379:6379"
    php:
        container_name: container_php
        build:
            context: php7-fpm
        volumes:
            - ./:/var/www/symfony
        links:
            - redis
    nginx:
        container_name: container_nginx
        build:
            context: nginx
        ports:
            - "80:80"
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    mysql:
        container_name: container_mysql
        image: mysql
        volumes:
            - "./.data/mysql:/var/lib/mysql"
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=homestead"
        ports:
            - "3306:3306"
    rabbit:
        container_name: container_rabbit
        hostname: rabbit
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        volumes:
            - ./.data/rabbitmq/:/var/lib/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"