send_message:
    path: /send/message
    controller: App\Controller\MessageController::send
    methods:    GET|POST

show_messages:
    path: /show/messages
    controller: App\Controller\MessageController::show
    methods:    GET

api_post_show:
    path:       /api/message/{id}
    controller: App\Controller\MessageController::updateStatus
    methods:    POST